#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "common.h"
#include "gc.h"

// entry generated by soc compiler
extern void soml_entry() RUNTIME_EXTERNAL(entry);


typedef struct {
  unsigned int heap_size;
} config;

void _parse_config(config* conf, int argc, char** argv) {
  if (argc != 2) {
    fprintf(stderr, "Usage: %s [heap_size]\n", argv[0]);
    exit(1);
  }
  conf->heap_size = atoi(argv[1]);
}

int main(int argc, char** argv) {
  config conf;
  _parse_config(&conf, argc, argv);
  gc_init(conf.heap_size);
  soml_entry();
}
