#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "common.h"
#include "gc.h"

// ~100mb
#define DEFAULT_HEAP_SIZE 100000000

// entry generated by soc compiler
extern void soml_entry() RUNTIME_EXTERNAL(entry);


typedef struct {
  unsigned int heap_size;
} config;

void _parse_config(config* conf, int argc, char** argv) {
  if (argc != 2) {
    conf->heap_size = DEFAULT_HEAP_SIZE;
  } else {
    conf->heap_size = atoi(argv[1]);
  }
}

int main(int argc, char** argv) {
  config conf;
  _parse_config(&conf, argc, argv);
  gc_init(conf.heap_size);
  soml_entry();
}
